// home page actions
export const LOG_IN = 'LOG_IN';
export const REGISTER = 'REGISTER';
export const SET_CURRENT_PROJECT_ID = 'SET_CURRENT_PROJECT_ID';

// project list actions
export const GET_PROJECTS_LIST = 'GET_PROJECTS_LIST';
export const GET_PROJECTS_LIST_FAILED = 'GET_PROJECTS_LIST_FAILED';
export const CHOSE_PROJECT = 'CHOSE_PROJECT';
export const ADD_PROJECT = 'ADD_PROJECT';
export const DUPLICATE_PROJECT = 'DUPLICATE_PROJECT';
export const SHARE_PROJECT = 'SHARE_PROJECT';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';
export const EDIT_NAME = 'EDIT_NAME';

// recognition tab
export const INIT_BATCH_RECOGNITION = 'INIT_BATCH_RECOGNITION';
export const INIT_FILE_RECOGNITION = 'INIT_BATCH_RECOGNITION';
export const DROP_FILES = 'DROP_FILES';
export const UPDATE_FILE_STATE = 'UPDATE_FILE_STATE';

// segmentation tab
export const INIT_BATCH_SEGMENTATION = 'INIT_BATCH_SEGMENTATION';
export const INIT_FILE_SEGMENTATION = 'INIT_BATCH_SEGMENTATION';
export const DROP_AUDIO_FILES = 'DROP_AUDIO_FILES';
export const DROP_TXT_FILES = 'DROP_TXT_FILES';
export const CHANGE_AUDIO_LIST_ORDER = 'CHANGE_AUDIO_LIST_ORDER';
export const CHANGE_TXT_LIST_ORDER = 'CHANGE_TXT_LIST_ORDER';

// repo
export const REPO_UPLOAD_FILE = 'REPO_UPLOAD_FILE';


