.ContainerFile{
    padding: 3px;
    padding-left:6px;
    border-bottom: 1px solid rgba(199,213,218,0) ;
    cursor: pointer;
 }

 .ContainerFile:hover{
    border-bottom: 1px solid #c7d5da;
 }

 .ContainerFile .repoIcon {
    margin-right: 8px;
    color: rgb(183, 198, 204);
    cursor: pointer;
  }

  .ContainerFile .repoIconMain {
    margin-right: 8px;
    color: rgb(124, 141, 148);
    cursor: pointer;
  }


  .ContainerFile .repoIcon:hover {
    color: rgb(119, 137, 148);
  }

  .ContainerFile .repoIcon.on {
    color: #28a745;
  }