.ContainerFile{
    padding: 3px;
    padding-left:22px;
    border-bottom: 1px solid rgba(199,213,218,0) ;
    cursor: pointer;
 }

 .ContainerFile.selected{
  background: #3498db;
  color: white;
}

 .ContainerFile:hover:not(.selected){
    background: #ccd9de;
 }

 .ContainerFile.selected .repoIcon {
   color: #bbdff7;
 }

 .ContainerFile .repoIcon {
    margin-right: 8px;
    color: rgb(183, 198, 204);
    cursor: pointer;
    font-size:0.9em;
  }

  .ContainerFile .repoIconMain {
    margin-right: 8px;
    cursor: pointer;
  }


  .ContainerFile .repoIcon:hover {
    color: rgb(119, 137, 148);
  }

  .ContainerFile .repoIcon.on {
    color: #1cce44;
  }

  .ContainerFile.selected .repoIcon {
    color: #80b9de;
  }

  .ContainerFile.selected .repoIcon.on {
    color:#00ff3a;
  }

 



  .ContainerFile .containerName {
    padding-right: 5px;
    padding-left: 5px;
    text-align: left;
  }